### ISSUE TITLE
Links/References to chapters in Introduction chapter missing in epub format

### ISSUE THREAD

**Issue by pprudhvi** [joaoventura/full-speed-python#10]
This is how the para is in epub format of the book.

“This book is divided in the following chapters: in chapter I will provide the basic installation instructions and execution of the Python interpreter. In chapter we will talk about the most basic data types, numbers and strings. In chapter we will start tinkering with functions, and in chapter the topic is about "loops". In chapter we will work with dictionaries and finally, in chapter we will finish the book with some exercises about classes and object oriented programming.”

**Comment by joaoventura** [comment]
Yes, I noticed it already, it seems that the convertion from latex to epub with pandoc does not take in account the references to the labels in each chapter.

**Comment by bluszcz** [comment]
There are some notes here:
 * http://pandoc.org/MANUAL.html#extension-citations
 * https://stackoverflow.com/questions/32236581/references-section-missing-from-table-of-content-in-epub-generated-with-pandoc

**Comment by joaoventura** [comment]
@bluszcz these are references to citations, the problem here is references to labels. For instance, [here is the label](https://github.com/joaoventura/full-speed-python/blob/master/chapters/installation.tex#L1) (\label{installation}) that identifies the installation chapter, and [here is where the reference to the installation chapter](https://github.com/joaoventura/full-speed-python/blob/master/chapters/introduction.tex#L7) (\ref{installation}) is being invoked.

Pandoc is not handling well the references to latex labels.. 🤔

**Comment by JoshuaAdrianJones** [comment]
You can use the pandoc-fignos filter for figure numbering and referencing. It works with any output format -- not just LaTeX.

Add a label to the image's attributes like this:

``` ![Caption.](image.png) {#fig:description}```

 and then reference the figure like this: 

 ```@fig:description```

Information on how to install and apply the pandoc-fignos filter is given on its Web page. There is also the pandoc-eqnos filter for doing the same kind of thing with equations.

[Source](https://stackoverflow.com/a/29069853)

>Can we use this as a fallback/alternative to latex labels for referencing sections of text?

**Comment by joaoventura** [comment]
@JoshuaAdrianJones It sounds feasible, do you think you could provide a working pull request?

**Comment by joaoventura** [comment]
I've removed the references to the chapters in the introduction, I'll be closing this issue..
